# Generated by Django 5.1.6 on 2025-03-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nobitex_currencies', models.CharField(max_length=255)),
                ('wallex_currencies', models.CharField(max_length=255)),
                ('common_currencies', models.CharField(max_length=255)),
                ('id_currencies', models.IntegerField()),
                ('nobitex_last_ask_price', models.FloatField()),
            ],
            options={
                'db_table': 'prices',
                'managed': False,
            },
        ),
    ]
